#!/usr/bin/env bash
#This script "manages manage_my_process"
start() {
	./manage_my_process & proc=$(pidof ./manage_my_process)
	echo "$proc" > /var/run/my_process.pid
	echo "manage_my_process started"
}

stop() {
	proc=$(pidof ./manage_my_process)
	kill -9 "$proc" && rm /var/run/my_process.pid
	echo "manage_my_process stopped"
}

restart() {
	proc=$(pidof ./manage_my_process)
	kill -9 "$proc" && rm /var/run/my_process.pid
	./manage_my_process &  
        echo "$proc" > /var/run/my_process.pid
	echo "manage_my_process restarted"
}

case "$1" in
	start)
		start
		;;
	stop) 
		stop
		;;
	restart)
		restart
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
esac

