#!/usr/bin/env bash
# This script display To infinity and beyond indefinitely//With a sleep 2 in between each iteration//I am invincible!!! when receiving a SIGTERM signal
i=1
while [ $i -le 3 ] 
do
	echo "To infinity and beyond"
	trap 'echo I am invincible!!!' 9
	sleep 2
done
